### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ZigmundVonZaun** [ZigmundVonZaun/little-bird#4]

**Comment by ZigmundVonZaun** [comment]
print() is not logging

**Comment by ColaLight77** [comment]
I saw you were using the logbook library instead of the Python standard one. Why is this?

**Comment by ColaLight77** [comment]
logbook removes most of the boilerplate. sweet library https://logbook.readthedocs.io/en/stable/

**Comment by ColaLight77** [comment]
Hi, have you taken a look Ken @Ken ?

**Comment by ZigmundVonZaun** [comment]
Yes. The Python standard logging library has a lot of boiler plate I dont feel like writing
