### ISSUE TITLE
Write boostrapping helper script

### ISSUE THREAD

**Issue by ZigmundVonZaun** [ZigmundVonZaun/little-bird#5]

**Comment by ZigmundVonZaun** [comment]
Instead of manually entering seeds, can we recursively scan the network and detect pre-exisiting instances of the overlay network?

**Comment by FadyDev2** [comment]
Yes. I can work on this. Do you suggest pinging all addresses in the local network using the Python library or we can just outsource everything to nmap?

**Comment by FadyDev2** [comment]
I have an idea. Maybe we can try pinging the broadcast address and have a magic packet sent to all the hosts in the networks. If they have our instance running, they can contact us back at the source address

**Comment by ColaLight77** [comment]
Isnt this just a smurf attack but you took out all the evil parts? Bad fady hahaha

**Comment by ZigmundVonZaun** [comment]
you guys are hilarious. lets just use nmap to scan. though it will take forever!

**Comment by ColaLight77** [comment]
can u explain over the phone pls to me @FadyDev2  i dont understand it
