### ISSUE TITLE
Maybe integrate Travis CI into our pipeline?

### ISSUE THREAD

**Issue by ZigmundVonZaun** [ZigmundVonZaun/little-bird#7]
Its free for public projects I think

**Comment by ColaLight77** [comment]
hm do we need continous integration? i think lets build and deploy once and be done with the project

**Comment by ColaLight77** [comment]
like, integration testing, unit testing, rollout to pi's and hopefully works fine in that environment

**Comment by ZigmundVonZaun** [comment]
okay
